Remove invalid property value
This fixes the following error when using this eslint config:
```
Error: .eslintrc » @xoi/eslint-config-core » /Users/timyager/code/SPIKES/net-auth-graphql-client/node_modules/@xoi/eslint-config-core/rules/import.js:
	Configuration for rule "import/no-unused-modules" is invalid:
	Value [] should NOT have fewer than 1 items.
```